### ISSUE TITLE
A quesion need help: ChangeLog only has one

### ISSUE THREAD

**Issue by stars-one** [loopwerk/tag-changelog#7]
I just copy the sample workflow code,but when I push a tag to the github,although the workflow work success,the release page only has a record.

I want this option:

> It can generate all of commit messages between the latest tag version and the previous tag version when i push a tag version.

**Detail sample:**
> Now my github repositiy has a tag named 0.2.And I publish a tag named 0.3.And there are 7 commit in two tag version.And the release body message also generate 7 commit message .

You may see my reposity,link is https://github.com/stars-one/kxorm

Hope your help,Thanks!

**Workflow code**:
```
name: Create Release

on:
  push:
    tags:
      - '*'

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create changelog text
        id: changelog
        uses: loopwerk/tag-changelog@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          exclude_types: other,doc,chore

      - name: Create release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ steps.changelog.outputs.changes }} 
```
